# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: SORA
subtitle: M-S's Blog
description: In solitude,where we are least alone.
author: Mashiro_Sorata
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mashirosorata.vicp.io
root: /
#permalink: :year/:month/:day/:title/
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "baidu_verify_CVB4TujEOt.html"
  - "google24611fe8e722fc62.html"
  - "README.md"
  - "CNAME"
  - "robots.txt"
  - "wallpaper-demo/**"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Extensions
## Plugins: https://hexo.io/plugins/
plugins: hexo-generate-feed
## Themes: https://hexo.io/themes/
theme: next

#live2d宠物
live2d:
  model: koharu
  bottom: -30
  #width: 宽度 默认值: 150
  #height: 高度 默认值：300
  #className: <canvas> 元素的类名 默认值： live2d
  #id: mylive 元素的id 默认值： live2dcanvas

# backup:
#     type: git
#     repository: github.com/Mashiro-Sorata/WhiteBackup.git
#     github: git@github.com:Mashiro-Sorata/WhiteBackup,master
#     #gitcafe: git@github.com:xxx/xxx.git,branchName

# Sitemap Setting
sitemap:
 path: sitemap.xml

baidusitemap:
 path: baidusitemap.xml


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:Mashiro-Sorata/Mashiro-Sorata.github.io.git
  branch: master
